POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "I love MongoDB", 
  "author": "Theo",
  "url": "https://backendmasters.com", 
  "likes": 1000
}

  # title: String,
  # author: String,
  # url: String,
  # likes: Number,