POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhYXdhMiIsImlkIjoiNjBjNGUxMDlmYTViYTEwZWNkZTIyMGIyIiwiaWF0IjoxNjIzNzg0NjA1LCJleHAiOjE2MjM3ODgyMDV9.L_kVzRO3Jl5aPEieUf-pXsU4GH3Z7YazGPNY37FjRA0

{
  "title": "Bearer and user tokens from middleware test Post", 
  "author": "Theo",
  "url": "https://fullstackopen.com", 
  "likes": 34
}

  # title: String,
  # author: String,
  # url: String,
  # likes: Number,