POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Dunno number 2", 
  "author": "Charlie",
  "url": "https://fullstackopen.com", 
  "likes": 65,
  "userId": "60c3ee9d14a338075dc91612"

}

  # title: String,
  # author: String,
  # url: String,
  # likes: Number,