
PUT http://localhost:3003/api/blogs/60c4d4fdf005d30b66c4ffa9
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhYXdhMiIsImlkIjoiNjBjNGUxMDlmYTViYTEwZWNkZTIyMGIyIiwiaWF0IjoxNjIzNzg0NjA1LCJleHAiOjE2MjM3ODgyMDV9.L_kVzRO3Jl5aPEieUf-pXsU4GH3Z7YazGPNY37FjRA0

{
  "title": "PUT test 2",
  "author": "myself",
  "url": "https://upatestuff.com",
  "likes": 9
}

